sudo: required
dist: trusty
language: node_js
node_js:
  - '8.11.1'

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

before_script:
- npm install -g angular-cli
- npm install @agm/core --save
- npm install rxjs@6 rxjs-compat@6 --save
- npm install -g karma
- npm install
- ng build

script: 
#- node_modules/karma/bin/karma start src/karma.conf.js --single-run
- ng test --karma-config src/karma.conf.js
